# Site settings
title: Building Blocks
header-img: img/home-bg.png
email: learn@heislercreative.com
copyright_name: heislercreative
description: > # this means to ignore newlines until "baseurl:"
  Developing: from idea to reality
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  heislercreative
learn_profile: heislercreative
email_username: learn@heislercreative.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
